=== GeoViQua/emulatorization-api/src/main/resources/emulator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://uncertws.aston.ac.uk/emulatorization"
	xmlns:e="http://uncertws.aston.ac.uk/emulatorization" elementFormDefault="qualified">

	<element name="Emulator" type="e:EmulatorType"/>

	<complexType name="EmulatorType">
		<sequence>
      <element name="inputs">
        <complexType>
          <choice maxOccurs="unbounded">
            <element name="FixedInput" type="e:FixedInputType" />
            <element name="VariableInput" type="e:VariableInputType" />
          </choice>
        </complexType>
      </element>
      <element name="outputs">
        <complexType>
          <sequence>
            <element name="Output" type="e:OutputType" maxOccurs="unbounded" />
          </sequence>
        </complexType>
      </element>
			<element name="design">
				<complexType>
					<sequence>
					  <element name="size" type="integer" />
						<element name="DesignInput"
							type="e:DesignInputType" maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>
			<element name="evaluationResult">
				<complexType>
					<sequence>
						<element name="EvaluationOutput" type="e:EvaluationOutputType" maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>
			<element name="meanFunction">
				<simpleType>
					<restriction base="string">
						<enumeration value="zero" />
						<enumeration value="constant" />
						<enumeration value="linear" />
						<enumeration value="quadratic" />
					</restriction>
				</simpleType>
			</element>
			<element name="covarianceFunction">
				<simpleType>
					<restriction base="string">
						<enumeration value="squared_exponential" />
						<enumeration value="matern" />
					</restriction>
				</simpleType>
			</element>
			<element name="lengthScales">
				<simpleType>
					<list itemType="double" />
				</simpleType>
			</element>
			<element name="nuggetVariance" type="double" maxOccurs="1" minOccurs="0">
			</element>
		</sequence>
	</complexType>

    <complexType name="EvaluationOutputType">
    	<sequence>
    		<element name="identifier" type="string"></element>
    		<element name="results">
    			<simpleType>
    				<list itemType="double" />
    			</simpleType>
    		</element>
    		<element name="mean" type="double" maxOccurs="1" minOccurs="0"></element>
    		<element name="stdDev" type="double" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="DesignInputType">
      <sequence>
        <element name="identifier" type="string"></element>
        <element name="points">
          <simpleType>
            <list itemType="double" />
          </simpleType>
        </element>
        <element name="mean" type="double" maxOccurs="1" minOccurs="0"></element>
        <element name="stdDev" type="double" maxOccurs="1" minOccurs="0"></element>
      </sequence>
    </complexType>

    <complexType name="InputType">
    	<sequence>
    		<element name="identifier" type="string"></element>
    		<element name="description" type="e:DescriptionType"></element>
    	</sequence>
    </complexType>
    
    <complexType name="OutputType">
    	<sequence>
    		<element name="identifier" type="string"></element>
    		<element name="description" type="e:DescriptionType"></element>
    	</sequence>
    </complexType>

    <complexType name="DescriptionType">
    	<sequence>
    		<element name="dataType">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="Numeric" />
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="encodingType">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="double" />
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="detail" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="uom" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="FixedInputType">
    	<complexContent>
    		<extension base="e:InputType">
    			<sequence>
    				<element name="value" type="double"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="VariableInputType">
    	<complexContent>
    		<extension base="e:InputType">
    			<sequence>
    				<element name="min" type="double"></element>
    				<element name="max" type="double"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
</schema>

=== GeoViQua/emulatorization-api/src/test/resources/polyfun-emulator.xml
<?xml version="1.0" encoding="UTF-8"?>
<e:Emulator xmlns:e="http://uncertws.aston.ac.uk/emulatorization" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://uncertws.aston.ac.uk/emulatorization ../../main/resources/emulator.xsd ">
  <e:inputs>
    <e:VariableInput>
      <e:identifier>A</e:identifier>
      <e:description>
        <e:dataType>Numeric</e:dataType>
        <e:encodingType>double</e:encodingType>
      </e:description>
      <e:min>100.0</e:min>
      <e:max>1000.0</e:max>
    </e:VariableInput>
    <e:FixedInput>
      <e:identifier>B</e:identifier>
      <e:description>
        <e:dataType>Numeric</e:dataType>
        <e:encodingType>double</e:encodingType>
      </e:description>
      <e:value>10.0</e:value>
    </e:FixedInput>
  </e:inputs>
  <e:outputs>
    <e:Output>
      <e:identifier>Result</e:identifier>
      <e:description>
        <e:dataType>Numeric</e:dataType>
        <e:encodingType>double</e:encodingType>
      </e:description>
    </e:Output>
  </e:outputs>
  <e:design>
    <e:size>19</e:size>
    <e:DesignInput>
      <e:identifier>A</e:identifier>
      <e:points>0.044105134037608434 1.0862515960189283 0.17036079398722329 -0.25811798858893437 1.4097711676147802 -0.3718586232890861 -1.0803630416479106 1.3535234401245368 -0.5344533659869191 -1.682585422528318 -0.7863240463477349 -1.5223139944387862 1.032957387960308 0.4947070204403414 1.2856161310505856 0.29430247509314544 -1.4128194955782534 -0.19952584946178428 0.676766681540267</e:points>
      <e:mean>609.2421260105268</e:mean>
      <e:stdDev>255.94192335091222</e:stdDev>
    </e:DesignInput>
    <e:DesignInput>
      <e:identifier>B</e:identifier>
      <e:points>-1.3885041165825702 -0.3121968140052109 0.5153221968724334 -0.8681205762352282 -0.12341973605086237 0.2618209024627499 1.2586597325720505 1.7045490548717706 -0.48901571999394144 -1.5376974764593037 -0.774248197521005 -0.4308905294231598 1.6780839427782452 -0.07230604394425845 0.17248462723062516 -1.126776354121118 1.4240914796907254 -0.5934797330402614 0.7016433608983205</e:points>
      <e:mean>12.321443774563392</e:mean>
      <e:stdDev>1.4743670710115735</e:stdDev>
    </e:DesignInput>
  </e:design>
  <e:evaluationResult>
    <e:EvaluationOutput>
      <e:identifier>Result</e:identifier>
      <e:results>-0.018569090941013357 1.0547483917392582 0.19023153298458378 -0.29572874490227724 1.3825165359451983 -0.35710774101344017 -1.0053482990068185 1.4204337905968438 -0.552100154872308 -1.7278697652969737 -0.8129056858511955 -1.524160428174668 1.1026773693955993 0.4820714327663267 1.2738798359802035 0.23865587032453897 -1.3243874566565597 -0.22622129890450146 0.6991839058872024</e:results>
      <e:mean>1981.6037046519125</e:mean>
      <e:stdDev>778.2534230469081</e:stdDev>
    </e:EvaluationOutput>
  </e:evaluationResult>
  <e:meanFunction>linear</e:meanFunction>
  <e:covarianceFunction>matern</e:covarianceFunction>
  <e:lengthScales>9.716755721742073 3.2527577743261773</e:lengthScales>
</e:Emulator>
